.github/workflows/publish.yml

modified runner to use ubuntu latest and removed matrix strategy
---
---
- Change 1
- Change 2
- ...
- ...

fix: modified runner

---

.github/workflows/publish.yml

changed github action to support image id
---
---
- Change 1
- Change 2
- ...
- ...

feat: image id

---

.aws/uat-task-definition.json

updated task-def to use build platform used by github actions
---
---
- Change 1
- Change 2
- ...
- ...

fix: github action platform

---

.github/workflows/publish.yml

I modified the release action to use warpbuild for builind the image
---
---
- Change 1
- Change 2
- ...
- ...

feat: adding warpbuild

---

docker/start.sh

new cert for uat
---
---
- Change 1
- Change 2
- ...
- ...

feat: new cert

---

.aws/prod-task-definition.json

updated task def to reference prod container
---
---
- Change 1
- Change 2
- ...
- ...

fix: update task-def

---

apps/web/src/app/(signing)/sign/[token]/complete/page.tsx
apps/web/src/app/(signing)/sign/[token]/form.tsx
apps/web/src/app/globals.css
apps/web/src/components/formatter/locale-date.tsx
packages/app-tests/e2e/templates/create-document-from-template.spec.ts
packages/lib/client-only/hooks/use-field-page-coords.ts
packages/lib/server-only/document/send-completed-email.ts

BKM-215, BKM-220
---
---
- Change 1
- Change 2
- ...
- ...

fix: string updates, locale hydrating issue

---

apps/web/src/app/(dashboard)/documents/upload-document.tsx
apps/web/src/app/globals.css
apps/web/src/components/(dashboard)/avatar/stack-avatars-with-tooltip.tsx

BKM-219, BKM-225
---
---
- Change 1
- Change 2
- ...
- ...

fix: documenso styling updates

---

apps/web/src/app/(dashboard)/documents/upload-document.tsx
apps/web/src/app/globals.css
apps/web/src/components/(dashboard)/avatar/stack-avatars-with-tooltip.tsx

BKM-219, BKM-225
---
---
- Change 1
- Change 2
- ...
- ...

fix: Documenso elements styling

---

.github/workflows/publish.yml

changed cluster name
---
---
- Change 1
- Change 2
- ...
- ...

fix: cluster name

---

apps/web/src/app/(signing)/sign/[token]/complete/page.tsx
apps/web/src/app/(unauthenticated)/articles/signature-disclosure/page.tsx
apps/web/src/app/globals.css
packages/email/template-components/template-document-completed.tsx

BKM-216, BKM-232, BKM-234
---
---
- Change 1
- Change 2
- ...
- ...

feat: adding minor changes after internal release

---

apps/web/src/app/(dashboard)/documents/upload-document.tsx

---
---
- Change 1
- Change 2
- ...
- ...

fix: adding loading indicator after doc upload

---

apps/web/src/app/(dashboard)/documents/upload-document.tsx

---
---
- Change 1
- Change 2
- ...
- ...

fix: loading indicator - quick fix

---

apps/web/src/app/(dashboard)/documents/upload-document.tsx

BKM-241
---
---
- Change 1
- Change 2
- ...
- ...

fix: loading indicator: quick fix

---

packages/ui/primitives/document-flow/add-signers.tsx
packages/ui/primitives/template-flow/add-template-settings.tsx
packages/ui/primitives/template-flow/add-template-settings.tsx~

BKM-214
---
---
- Change 1
- Change 2
- ...
- ...

feat: modify document  setup fields bkm 214

---

apps/web/src/app/(dashboard)/documents/upload-document.tsx
packages/ui/primitives/document-flow/add-signers.tsx
packages/ui/primitives/template-flow/add-template-settings.tsx
packages/ui/primitives/template-flow/add-template-settings.tsx~

---
---
- Change 1
- Change 2
- ...
- ...

feat: modify document signing setup

---

packages/ui/primitives/document-flow/add-fields.tsx
packages/ui/primitives/document-flow/add-signers.tsx
packages/ui/primitives/template-flow/add-template-fields.tsx

BKM-214
---
---
- Change 1
- Change 2
- ...
- ...

feat: modify document setup

---

apps/web/src/app/(dashboard)/documents/[id]/edit-document.tsx

BKM-246
---
---
- Change 1
- Change 2
- ...
- ...

feat: text updates

---

packages/trpc/server/auth-router/schema.ts

---
---
- Change 1
- Change 2
- ...
- ...

fix: investigating to fix the issue with .com

---

apps/web/src/app/(dashboard)/documents/upload-document.tsx

---
---
- Change 1
- Change 2
- ...
- ...

fix: investigating the issue on .com

---

apps/web/src/app/(dashboard)/documents/upload-document.tsx
packages/lib/next-auth/auth-options.ts
packages/trpc/server/auth-router/schema.ts

---
---
- Change 1
- Change 2
- ...
- ...

fix: investigating to fix .com issue

---

apps/web/src/middleware.ts

---
---
- Change 1
- Change 2
- ...
- ...

fix: trying to fix .com version

---

apps/marketing/next.config.js
apps/web/src/middleware.ts
packages/lib/next-auth/auth-options.ts

---
---
- Change 1
- Change 2
- ...
- ...

Com domain

---

apps/web/next.config.js

added hardcoded urls for cors
---
---
- Change 1
- Change 2
- ...
- ...

fix: can't access env var in config

---

apps/web/src/app/(signing)/sign/[token]/complete/page.tsx

---
---
- Change 1
- Change 2
- ...
- ...

fix: fixing signing process issue bkm 274

---

apps/marketing/next.config.js
apps/web/src/middleware.ts

---
---
- Change 1
- Change 2
- ...
- ...

fix: hiding the claiming account

---

apps/web/src/app/(dashboard)/documents/upload-document.tsx

The extra additions/deletions are the js formatter

fix: changed error message from large file size to only pdf files are accepted

---

apps/web/src/app/(unauthenticated)/articles/signature-disclosure/page.tsx
docker/development/compose.yml

---
---
- Change 1
- Change 2
- ...
- ...

chore: updated signing disclosure for documenso release.com

---

apps/web/src/app/(dashboard)/documents/upload-document.tsx

Doubled toast duration, modified the error message
---
---
- Change 1
- Change 2
- ...
- ...

chore: Update upload-document.tsx

---

packages/lib/server-only/document/complete-document-with-token.ts
turbo.json

@jasonong  - Added call to backend to capture signing state

Added call to backend to capture signing state

---

apps/web/src/app/(dashboard)/documents/[id]/edit-document.tsx

---
---
- Change 1
- Change 2
- ...
- ...

refactor: update edit-document.tsx
